name: bookly_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  fancy_text_reveal: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  go_router: ^9.1.1
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/Book1.png
  fonts:
    - family: GTSectraFine
      fonts:
        - asset: assets/fonts/GTSectraFine-Regular.ttf
          weight: 400
